/*
===============================================================================
Project Name : E-Commerce Sales Analysis using SQL Server

File Name    : 12_Payment_Analysis.sql

Author       : Mayur Sandip Mali

Description  :
This script analyzes customer payment behavior, payment methods,
installments, revenue contribution, and payment trends.

Database     : EcommerceDB
===============================================================================
*/


/*==============================================================================
Business Question 1:
What is the total revenue generated by each payment method?
==============================================================================*/
SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS Total_Revenue
FROM raw_payments
GROUP BY payment_type
ORDER BY Total_Revenue DESC;
/*
Business Insight:
• Identifies which payment methods contribute the highest revenue.
• Helps finance teams optimize payment gateway partnerships.
*/


/*==============================================================================
Business Question 2:
How many transactions were made using each payment method?
==============================================================================*/
SELECT
    payment_type,
    COUNT(*) AS Total_Transactions
FROM raw_payments
GROUP BY payment_type
ORDER BY Total_Transactions DESC;
/*
Business Insight:
• Shows customer preference for different payment methods.
*/


/*==============================================================================
Business Question 3:
What is the average payment value for each payment method?
==============================================================================*/
SELECT
    payment_type,
    ROUND(AVG(payment_value),2) AS Average_Payment
FROM raw_payments
GROUP BY payment_type
ORDER BY Average_Payment DESC;
/*
Business Insight:
• Indicates which payment methods are associated with higher-value purchases.
*/


/*==============================================================================
Business Question 4:
How many installment options do customers use?
==============================================================================*/
SELECT
    payment_installments,
    COUNT(*) AS Total_Transactions
FROM raw_payments
GROUP BY payment_installments
ORDER BY payment_installments;
/*
Business Insight:
• Reveals customer preference for installment-based purchases.
*/


/*==============================================================================
Business Question 5:
Average payment value by installment count
==============================================================================*/
SELECT
    payment_installments,
    ROUND(AVG(payment_value),2) AS Average_Payment
FROM raw_payments
GROUP BY payment_installments
ORDER BY payment_installments;
/*
Business Insight:
• Higher installment counts often correspond to higher purchase values.
*/


/*==============================================================================
Business Question 6:
Top 10 Highest Payments
==============================================================================*/
SELECT TOP 10
    order_id,
    payment_type,
    payment_installments,
    payment_value
FROM raw_payments
ORDER BY payment_value DESC;
/*
Business Insight:
• Identifies the highest-value customer transactions.
*/


/*==============================================================================
Business Question 7:
Revenue Contribution (%) by Payment Method
==============================================================================*/
SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS Revenue,
    ROUND(
        SUM(payment_value) * 100.0 /
        (SELECT SUM(payment_value) FROM raw_payments),
        2
    ) AS Revenue_Percentage
FROM raw_payments
GROUP BY payment_type
ORDER BY Revenue DESC;
/*
Business Insight:
• Shows the percentage contribution of each payment method
  to total revenue.
*/


/*==============================================================================
Business Question 8:
Rank Payment Methods by Revenue
==============================================================================*/
SELECT
    payment_type,
    SUM(payment_value) AS Revenue,
    RANK() OVER
    (
        ORDER BY SUM(payment_value) DESC
    ) AS Revenue_Rank
FROM raw_payments
GROUP BY payment_type;
/*
Business Insight:
• Ranks payment methods based on revenue generation.
*/


/*==============================================================================
Business Question 9:
Monthly Revenue by Payment Method
==============================================================================*/
SELECT
    YEAR(o.order_purchase_timestamp) AS Order_Year,
    MONTH(o.order_purchase_timestamp) AS Order_Month,
    p.payment_type,
    ROUND(SUM(p.payment_value),2) AS Revenue
FROM raw_orders o
JOIN raw_payments p
ON o.order_id = p.order_id
GROUP BY
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp),
    p.payment_type
ORDER BY
    Order_Year,
    Order_Month,
    Revenue DESC;
/*
Business Insight:
• Tracks monthly payment trends across payment methods.
• Useful for financial forecasting.
*/


/*==============================================================================
Business Question 10:
Top 5 Orders with Multiple Payments
==============================================================================*/
SELECT TOP 5
    order_id,
    COUNT(*) AS Number_of_Payments,
    ROUND(SUM(payment_value),2) AS Total_Paid
FROM raw_payments
GROUP BY order_id
HAVING COUNT(*) > 1
ORDER BY Number_of_Payments DESC;
/*
Business Insight:
• Some orders are paid using multiple payment records.
• Indicates split payments or multiple payment attempts.
*/


/*==============================================================================
Business Question 11:
Payment Statistics
==============================================================================*/
SELECT
    COUNT(*) AS Total_Payments,
    ROUND(SUM(payment_value),2) AS Total_Revenue,
    ROUND(AVG(payment_value),2) AS Average_Payment,
    MIN(payment_value) AS Minimum_Payment,
    MAX(payment_value) AS Maximum_Payment
FROM raw_payments;
/*
Business Insight:
• Provides a quick summary of payment performance.
*/


/*==============================================================================
Business Question 12:
Top 10 Customers by Total Payment
==============================================================================*/
SELECT TOP 10
    c.customer_unique_id,
    ROUND(SUM(p.payment_value),2) AS Total_Spent
FROM raw_customers c
JOIN raw_orders o
ON c.customer_id = o.customer_id
JOIN raw_payments p
ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY Total_Spent DESC;
/*
Business Insight:
• Identifies the highest spending customers.
• Useful for VIP customer programs and loyalty initiatives.
*/


/*==============================================================================
PAYMENT ANALYSIS SUMMARY
==============================================================================
Key Findings:

• Identified the most popular payment methods.
• Compared revenue generated by each payment type.
• Analyzed customer installment preferences.
• Ranked payment methods using window functions.
• Identified high-value payments and top spending customers.
• Tracked monthly payment trends.
• Generated overall payment statistics.

Business Value:

This analysis helps understand customer payment behavior,
optimize payment options, improve financial planning,
and identify valuable customers for targeted marketing.

==============================================================================
*/